import * as React from 'react';
import { Command as CommandPrimitive } from 'cmdk';
import { Search } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from './dialog';
import { cn } from '@/lib/utils';

export const Command = React.forwardRef<React.ElementRef<typeof CommandPrimitive>, React.ComponentPropsWithoutRef<typeof CommandPrimitive>>(({ className, ...props }, ref) => <CommandPrimitive ref={ref} className={cn('flex h-full w-full flex-col overflow-hidden rounded-lg bg-background text-foreground', className)} {...props} />);
export function CommandDialog({ open, onOpenChange, children }: { open: boolean; onOpenChange(open: boolean): void; children: React.ReactNode }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-[580px] gap-0 overflow-hidden p-0"><DialogTitle className="sr-only">Commands</DialogTitle><DialogDescription className="sr-only">Search projects and actions.</DialogDescription><Command>{children}</Command></DialogContent></Dialog>;
}
export const CommandInput = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Input>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Input>>(({ className, ...props }, ref) => <div className="flex items-center gap-2 border-b px-4"><Search className="size-4 shrink-0 text-muted-foreground" /><CommandPrimitive.Input ref={ref} className={cn('h-12 w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground', className)} {...props} /></div>);
export const CommandList = React.forwardRef<React.ElementRef<typeof CommandPrimitive.List>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.List>>(({ className, ...props }, ref) => <CommandPrimitive.List ref={ref} className={cn('max-h-[min(60vh,420px)] overflow-y-auto p-2', className)} {...props} />);
export const CommandEmpty = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Empty>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Empty>>(({ className, ...props }, ref) => <CommandPrimitive.Empty ref={ref} className={cn('py-8 text-center text-sm text-muted-foreground', className)} {...props} />);
export const CommandGroup = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Group>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Group>>(({ className, ...props }, ref) => <CommandPrimitive.Group ref={ref} className={cn('py-1 text-foreground [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-[10px] [&_[cmdk-group-heading]]:font-semibold [&_[cmdk-group-heading]]:uppercase [&_[cmdk-group-heading]]:tracking-wider [&_[cmdk-group-heading]]:text-muted-foreground', className)} {...props} />);
export const CommandItem = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Item>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>>(({ className, ...props }, ref) => <CommandPrimitive.Item ref={ref} className={cn('flex min-h-10 cursor-pointer items-center gap-3 rounded-md px-2 py-2 text-sm outline-none data-[selected=true]:bg-[var(--surface-hover)] data-[disabled=true]:opacity-50', className)} {...props} />);
export const CommandSeparator = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Separator>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Separator>>(({ className, ...props }, ref) => <CommandPrimitive.Separator ref={ref} className={cn('my-1 h-px bg-border', className)} {...props} />);
export function CommandShortcut({ className, ...props }: React.HTMLAttributes<HTMLSpanElement>) { return <span className={cn('ml-auto text-[11px] text-muted-foreground', className)} {...props} />; }
